"""
This example is to demonstrate how views/routes that were
not created by AutoDojo can be included in a Ninja API
"""

from django.http import HttpRequest
from ninja import Router

from books_api.models import Book

router = Router(tags=["Book"])


@router.get("/{int:id}/authors", response={200: list[int]})
def get_book_authors(request: HttpRequest, id: int):
    """
    This endpoint was manually added to demonstrate that normal
    use of view functions can work alongside those automatically
    generated by AutoDojo
    """
    authors = Book.objects.get(pk=id).authors.values_list("id")
    author_ids = [a[0] for a in authors]
    return author_ids
