# Generated by Django 5.0.6 on 2024-06-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13),
        ),
    ]
