# Generated by Django 5.0.6 on 2024-06-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books_api", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
